/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyCheckIn {
  'completedTasks' : Array<Task>,
  'missedTasks' : Array<Task>,
  'date' : bigint,
  'goalId' : bigint,
}
export interface Goal {
  'id' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'lockedIn' : boolean,
  'motivation' : string,
  'timeFrame' : Type__1,
}
export interface GoalProgress {
  'dailyTasks' : Array<Task>,
  'weeklyTasks' : Array<Task>,
  'milestones' : Array<Milestone>,
}
export interface Milestone { 'desc' : string, 'dueDate' : [] | [bigint] }
export interface Task {
  'desc' : string,
  'category' : [] | [Type],
  'isComplete' : boolean,
}
export type Type = { 'avoidance' : null } |
  { 'other' : null } |
  { 'lowEnergy' : null } |
  { 'distraction' : null } |
  { 'overplanning' : null };
export type Type__1 = { 'months6to12' : null } |
  { 'days30' : null } |
  { 'days90' : null } |
  { 'years1to5' : null };
export interface UserDataView {
  'weeklyPlans' : Array<[bigint, WeeklyPlan]>,
  'dailyCheckIns' : Array<DailyCheckIn>,
  'weeklyReviews' : Array<WeeklyReview>,
  'goalProgress' : Array<[bigint, GoalProgress]>,
  'goals' : Array<[bigint, Goal]>,
}
export interface UserProfile { 'name' : string, 'avatar' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyPlan {
  'completedTasks' : Array<Task>,
  'plannedTasks' : Array<Task>,
  'progressSummary' : string,
}
export interface WeeklyReview {
  'completedTasks' : Array<Task>,
  'plannedTasks' : Array<Task>,
  'goalId' : bigint,
  'progressSummary' : string,
  'weekStart' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyTasks' : ActorMethod<[bigint, Array<Task>], undefined>,
  'addMilestones' : ActorMethod<[bigint, Array<Milestone>], undefined>,
  'addWeeklyTasks' : ActorMethod<[bigint, Array<Task>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGoal' : ActorMethod<[string, Type__1, string], bigint>,
  'getAllUserData' : ActorMethod<[], Array<[Principal, UserDataView]>>,
  'getAllUserGoals' : ActorMethod<[], Array<[Principal, Array<Goal>]>>,
  'getAllWeeklyPlans' : ActorMethod<
    [],
    Array<[Principal, Array<[bigint, WeeklyPlan]>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyCheckIns' : ActorMethod<[], Array<DailyCheckIn>>,
  'getDailyCheckInsByGoal' : ActorMethod<[bigint], Array<DailyCheckIn>>,
  'getDailyTasks' : ActorMethod<[bigint], Array<Task>>,
  'getGoal' : ActorMethod<[bigint], [] | [Goal]>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getMilestones' : ActorMethod<[bigint], Array<Milestone>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyPlan' : ActorMethod<[bigint], [] | [WeeklyPlan]>,
  'getWeeklyPlansByGoal' : ActorMethod<[bigint], Array<WeeklyPlan>>,
  'getWeeklyReviews' : ActorMethod<[], Array<WeeklyReview>>,
  'getWeeklyReviewsByGoal' : ActorMethod<[bigint], Array<WeeklyReview>>,
  'getWeeklyTasks' : ActorMethod<[bigint], Array<Task>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isGoalLockedIn' : ActorMethod<[bigint], boolean>,
  'lockInGoal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDailyCheckIn' : ActorMethod<
    [bigint, Array<Task>, Array<Task>],
    undefined
  >,
  'submitWeeklyPlan' : ActorMethod<[bigint, Array<Task>, string], undefined>,
  'submitWeeklyReview' : ActorMethod<
    [bigint, Array<Task>, Array<Task>, string],
    undefined
  >,
  'updateWeeklyPlanProgress' : ActorMethod<[bigint, Array<Task>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];