/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Type = IDL.Variant({
  'avoidance' : IDL.Null,
  'other' : IDL.Null,
  'lowEnergy' : IDL.Null,
  'distraction' : IDL.Null,
  'overplanning' : IDL.Null,
});
export const Task = IDL.Record({
  'desc' : IDL.Text,
  'category' : IDL.Opt(Type),
  'isComplete' : IDL.Bool,
});
export const Milestone = IDL.Record({
  'desc' : IDL.Text,
  'dueDate' : IDL.Opt(IDL.Int),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type__1 = IDL.Variant({
  'months6to12' : IDL.Null,
  'days30' : IDL.Null,
  'days90' : IDL.Null,
  'years1to5' : IDL.Null,
});
export const WeeklyPlan = IDL.Record({
  'completedTasks' : IDL.Vec(Task),
  'plannedTasks' : IDL.Vec(Task),
  'progressSummary' : IDL.Text,
});
export const DailyCheckIn = IDL.Record({
  'completedTasks' : IDL.Vec(Task),
  'missedTasks' : IDL.Vec(Task),
  'date' : IDL.Int,
  'goalId' : IDL.Nat,
});
export const WeeklyReview = IDL.Record({
  'completedTasks' : IDL.Vec(Task),
  'plannedTasks' : IDL.Vec(Task),
  'goalId' : IDL.Nat,
  'progressSummary' : IDL.Text,
  'weekStart' : IDL.Int,
});
export const GoalProgress = IDL.Record({
  'dailyTasks' : IDL.Vec(Task),
  'weeklyTasks' : IDL.Vec(Task),
  'milestones' : IDL.Vec(Milestone),
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'lockedIn' : IDL.Bool,
  'motivation' : IDL.Text,
  'timeFrame' : Type__1,
});
export const UserDataView = IDL.Record({
  'weeklyPlans' : IDL.Vec(IDL.Tuple(IDL.Nat, WeeklyPlan)),
  'dailyCheckIns' : IDL.Vec(
    IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Int, DailyCheckIn)))
  ),
  'weeklyReviews' : IDL.Vec(WeeklyReview),
  'goalProgress' : IDL.Vec(IDL.Tuple(IDL.Nat, GoalProgress)),
  'goals' : IDL.Vec(IDL.Tuple(IDL.Nat, Goal)),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avatar' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyTasks' : IDL.Func([IDL.Nat, IDL.Vec(Task)], [], []),
  'addMilestones' : IDL.Func([IDL.Nat, IDL.Vec(Milestone)], [], []),
  'addWeeklyTasks' : IDL.Func([IDL.Nat, IDL.Vec(Task)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGoal' : IDL.Func([IDL.Text, Type__1, IDL.Text], [IDL.Nat], []),
  'createGoalWithCustomDuration' : IDL.Func(
      [IDL.Text, Type__1, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'getAllUserData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserDataView))],
      [],
    ),
  'getAllUserGoals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Goal)))],
      ['query'],
    ),
  'getAllWeeklyPlans' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Tuple(IDL.Nat, WeeklyPlan)))
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyCheckIns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Int, DailyCheckIn))))],
      ['query'],
    ),
  'getDailyCheckInsByGoal' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Int, DailyCheckIn))],
      ['query'],
    ),
  'getDailyTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(Goal)], ['query']),
  'getGoalDuration' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getMilestones' : IDL.Func([IDL.Nat], [IDL.Vec(Milestone)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyPlan' : IDL.Func([IDL.Nat], [IDL.Opt(WeeklyPlan)], ['query']),
  'getWeeklyPlansByGoal' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WeeklyPlan)],
      ['query'],
    ),
  'getWeeklyReviews' : IDL.Func([], [IDL.Vec(WeeklyReview)], ['query']),
  'getWeeklyReviewsByGoal' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WeeklyReview)],
      ['query'],
    ),
  'getWeeklyTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'goalExists' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isGoalLockedIn' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'lockInGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDailyCheckIn' : IDL.Func(
      [IDL.Nat, IDL.Vec(Task), IDL.Vec(Task)],
      [],
      [],
    ),
  'submitWeeklyPlan' : IDL.Func([IDL.Nat, IDL.Vec(Task), IDL.Text], [], []),
  'submitWeeklyReview' : IDL.Func(
      [IDL.Nat, IDL.Vec(Task), IDL.Vec(Task), IDL.Text],
      [],
      [],
    ),
  'updateWeeklyPlanProgress' : IDL.Func([IDL.Nat, IDL.Vec(Task)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Type = IDL.Variant({
    'avoidance' : IDL.Null,
    'other' : IDL.Null,
    'lowEnergy' : IDL.Null,
    'distraction' : IDL.Null,
    'overplanning' : IDL.Null,
  });
  const Task = IDL.Record({
    'desc' : IDL.Text,
    'category' : IDL.Opt(Type),
    'isComplete' : IDL.Bool,
  });
  const Milestone = IDL.Record({
    'desc' : IDL.Text,
    'dueDate' : IDL.Opt(IDL.Int),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type__1 = IDL.Variant({
    'months6to12' : IDL.Null,
    'days30' : IDL.Null,
    'days90' : IDL.Null,
    'years1to5' : IDL.Null,
  });
  const WeeklyPlan = IDL.Record({
    'completedTasks' : IDL.Vec(Task),
    'plannedTasks' : IDL.Vec(Task),
    'progressSummary' : IDL.Text,
  });
  const DailyCheckIn = IDL.Record({
    'completedTasks' : IDL.Vec(Task),
    'missedTasks' : IDL.Vec(Task),
    'date' : IDL.Int,
    'goalId' : IDL.Nat,
  });
  const WeeklyReview = IDL.Record({
    'completedTasks' : IDL.Vec(Task),
    'plannedTasks' : IDL.Vec(Task),
    'goalId' : IDL.Nat,
    'progressSummary' : IDL.Text,
    'weekStart' : IDL.Int,
  });
  const GoalProgress = IDL.Record({
    'dailyTasks' : IDL.Vec(Task),
    'weeklyTasks' : IDL.Vec(Task),
    'milestones' : IDL.Vec(Milestone),
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'lockedIn' : IDL.Bool,
    'motivation' : IDL.Text,
    'timeFrame' : Type__1,
  });
  const UserDataView = IDL.Record({
    'weeklyPlans' : IDL.Vec(IDL.Tuple(IDL.Nat, WeeklyPlan)),
    'dailyCheckIns' : IDL.Vec(
      IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Int, DailyCheckIn)))
    ),
    'weeklyReviews' : IDL.Vec(WeeklyReview),
    'goalProgress' : IDL.Vec(IDL.Tuple(IDL.Nat, GoalProgress)),
    'goals' : IDL.Vec(IDL.Tuple(IDL.Nat, Goal)),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'avatar' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyTasks' : IDL.Func([IDL.Nat, IDL.Vec(Task)], [], []),
    'addMilestones' : IDL.Func([IDL.Nat, IDL.Vec(Milestone)], [], []),
    'addWeeklyTasks' : IDL.Func([IDL.Nat, IDL.Vec(Task)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGoal' : IDL.Func([IDL.Text, Type__1, IDL.Text], [IDL.Nat], []),
    'createGoalWithCustomDuration' : IDL.Func(
        [IDL.Text, Type__1, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'getAllUserData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserDataView))],
        [],
      ),
    'getAllUserGoals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Goal)))],
        ['query'],
      ),
    'getAllWeeklyPlans' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Tuple(IDL.Nat, WeeklyPlan)))
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyCheckIns' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Int, DailyCheckIn)))
          ),
        ],
        ['query'],
      ),
    'getDailyCheckInsByGoal' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Int, DailyCheckIn))],
        ['query'],
      ),
    'getDailyTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(Goal)], ['query']),
    'getGoalDuration' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getMilestones' : IDL.Func([IDL.Nat], [IDL.Vec(Milestone)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyPlan' : IDL.Func([IDL.Nat], [IDL.Opt(WeeklyPlan)], ['query']),
    'getWeeklyPlansByGoal' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WeeklyPlan)],
        ['query'],
      ),
    'getWeeklyReviews' : IDL.Func([], [IDL.Vec(WeeklyReview)], ['query']),
    'getWeeklyReviewsByGoal' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WeeklyReview)],
        ['query'],
      ),
    'getWeeklyTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'goalExists' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isGoalLockedIn' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'lockInGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDailyCheckIn' : IDL.Func(
        [IDL.Nat, IDL.Vec(Task), IDL.Vec(Task)],
        [],
        [],
      ),
    'submitWeeklyPlan' : IDL.Func([IDL.Nat, IDL.Vec(Task), IDL.Text], [], []),
    'submitWeeklyReview' : IDL.Func(
        [IDL.Nat, IDL.Vec(Task), IDL.Vec(Task), IDL.Text],
        [],
        [],
      ),
    'updateWeeklyPlanProgress' : IDL.Func([IDL.Nat, IDL.Vec(Task)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };