/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Milestone {
    desc: string;
    dueDate?: bigint;
}
export interface GoalProgress {
    dailyTasks: Array<Task>;
    weeklyTasks: Array<Task>;
    milestones: Array<Milestone>;
}
export interface Goal {
    id: bigint;
    durationDays: bigint;
    createdAt: bigint;
    description: string;
    lockedIn: boolean;
    motivation: string;
    timeFrame: Type__1;
}
export interface DailyCheckIn {
    completedTasks: Array<Task>;
    missedTasks: Array<Task>;
    date: bigint;
    goalId: bigint;
}
export interface WeeklyPlan {
    completedTasks: Array<Task>;
    plannedTasks: Array<Task>;
    progressSummary: string;
}
export interface Task {
    desc: string;
    category?: Type;
    isComplete: boolean;
}
export interface WeeklyReview {
    completedTasks: Array<Task>;
    plannedTasks: Array<Task>;
    goalId: bigint;
    progressSummary: string;
    weekStart: bigint;
}
export interface UserProfile {
    name: string;
    avatar: string;
}
export interface UserDataView {
    weeklyPlans: Array<[bigint, WeeklyPlan]>;
    dailyCheckIns: Array<DailyCheckIn>;
    weeklyReviews: Array<WeeklyReview>;
    goalProgress: Array<[bigint, GoalProgress]>;
    goals: Array<[bigint, Goal]>;
}
export enum Type {
    avoidance = "avoidance",
    other = "other",
    lowEnergy = "lowEnergy",
    distraction = "distraction",
    overplanning = "overplanning"
}
export enum Type__1 {
    months6to12 = "months6to12",
    days30 = "days30",
    days90 = "days90",
    years1to5 = "years1to5"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDailyTasks(goalId: bigint, tasks: Array<Task>): Promise<void>;
    addMilestones(goalId: bigint, milestones: Array<Milestone>): Promise<void>;
    addWeeklyTasks(goalId: bigint, tasks: Array<Task>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGoal(description: string, timeFrame: Type__1, motivation: string): Promise<bigint>;
    createGoalWithCustomDuration(description: string, timeFrame: Type__1, motivation: string, durationDays: bigint): Promise<bigint>;
    deleteGoal(goalId: bigint): Promise<void>;
    getAllUserData(): Promise<Array<[Principal, UserDataView]>>;
    getAllUserGoals(): Promise<Array<[Principal, Array<Goal>]>>;
    getAllWeeklyPlans(): Promise<Array<[Principal, Array<[bigint, WeeklyPlan]>]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyCheckIns(): Promise<Array<DailyCheckIn>>;
    getDailyCheckInsByGoal(goalId: bigint): Promise<Array<DailyCheckIn>>;
    getDailyTasks(goalId: bigint): Promise<Array<Task>>;
    getGoal(goalId: bigint): Promise<Goal | null>;
    getGoalDuration(goalId: bigint): Promise<bigint | null>;
    getGoals(): Promise<Array<Goal>>;
    getMilestones(goalId: bigint): Promise<Array<Milestone>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyPlan(goalId: bigint): Promise<WeeklyPlan | null>;
    getWeeklyPlansByGoal(goalId: bigint): Promise<Array<WeeklyPlan>>;
    getWeeklyReviews(): Promise<Array<WeeklyReview>>;
    getWeeklyReviewsByGoal(goalId: bigint): Promise<Array<WeeklyReview>>;
    getWeeklyTasks(goalId: bigint): Promise<Array<Task>>;
    goalExists(goalId: bigint): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isGoalLockedIn(goalId: bigint): Promise<boolean>;
    lockInGoal(goalId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitDailyCheckIn(goalId: bigint, completedTasks: Array<Task>, missedTasks: Array<Task>): Promise<void>;
    submitWeeklyPlan(goalId: bigint, plannedTasks: Array<Task>, progressSummary: string): Promise<void>;
    submitWeeklyReview(goalId: bigint, plannedTasks: Array<Task>, completedTasks: Array<Task>, progressSummary: string): Promise<void>;
    updateWeeklyPlanProgress(goalId: bigint, completedTasks: Array<Task>): Promise<void>;
}
import type { DailyCheckIn as _DailyCheckIn, Goal as _Goal, GoalProgress as _GoalProgress, Milestone as _Milestone, Task as _Task, Type as _Type, Type__1 as _Type__1, UserDataView as _UserDataView, UserProfile as _UserProfile, UserRole as _UserRole, WeeklyPlan as _WeeklyPlan, WeeklyReview as _WeeklyReview } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDailyTasks(arg0: bigint, arg1: Array<Task>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyTasks(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyTasks(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addMilestones(arg0: bigint, arg1: Array<Milestone>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilestones(arg0, to_candid_vec_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilestones(arg0, to_candid_vec_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addWeeklyTasks(arg0: bigint, arg1: Array<Task>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeeklyTasks(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeeklyTasks(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGoal(arg0: string, arg1: Type__1, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, to_candid_Type__1_n11(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, to_candid_Type__1_n11(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async createGoalWithCustomDuration(arg0: string, arg1: Type__1, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoalWithCustomDuration(arg0, to_candid_Type__1_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoalWithCustomDuration(arg0, to_candid_Type__1_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async getAllUserData(): Promise<Array<[Principal, UserDataView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserData();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserData();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserGoals(): Promise<Array<[Principal, Array<Goal>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserGoals();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserGoals();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWeeklyPlans(): Promise<Array<[Principal, Array<[bigint, WeeklyPlan]>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWeeklyPlans();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWeeklyPlans();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyCheckIns(): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyCheckIns();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyCheckIns();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyCheckInsByGoal(arg0: bigint): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyCheckInsByGoal(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyCheckInsByGoal(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTasks(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTasks(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoal(arg0: bigint): Promise<Goal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoal(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoal(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoalDuration(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoalDuration(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoalDuration(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMilestones(arg0: bigint): Promise<Array<Milestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestones(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestones(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyPlan(arg0: bigint): Promise<WeeklyPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyPlan(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyPlan(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyPlansByGoal(arg0: bigint): Promise<Array<WeeklyPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyPlansByGoal(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyPlansByGoal(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyReviews(): Promise<Array<WeeklyReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyReviews();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyReviews();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyReviewsByGoal(arg0: bigint): Promise<Array<WeeklyReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyReviewsByGoal(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyReviewsByGoal(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyTasks(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyTasks(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async goalExists(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.goalExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.goalExists(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isGoalLockedIn(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isGoalLockedIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isGoalLockedIn(arg0);
            return result;
        }
    }
    async lockInGoal(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.lockInGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockInGoal(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitDailyCheckIn(arg0: bigint, arg1: Array<Task>, arg2: Array<Task>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDailyCheckIn(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDailyCheckIn(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async submitWeeklyPlan(arg0: bigint, arg1: Array<Task>, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWeeklyPlan(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWeeklyPlan(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async submitWeeklyReview(arg0: bigint, arg1: Array<Task>, arg2: Array<Task>, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWeeklyReview(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWeeklyReview(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateWeeklyPlanProgress(arg0: bigint, arg1: Array<Task>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeeklyPlanProgress(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeeklyPlanProgress(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DailyCheckIn_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyCheckIn): DailyCheckIn {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_GoalProgress_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalProgress): GoalProgress {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Milestone_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Milestone): Milestone {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserDataView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDataView): UserDataView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyPlan_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyPlan): WeeklyPlan {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyReview_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyReview): WeeklyReview {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Type]): Type | null {
    return value.length === 0 ? null : from_candid_Type_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Goal]): Goal | null {
    return value.length === 0 ? null : from_candid_Goal_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeeklyPlan]): WeeklyPlan | null {
    return value.length === 0 ? null : from_candid_WeeklyPlan_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weeklyPlans: Array<[bigint, _WeeklyPlan]>;
    dailyCheckIns: Array<_DailyCheckIn>;
    weeklyReviews: Array<_WeeklyReview>;
    goalProgress: Array<[bigint, _GoalProgress]>;
    goals: Array<[bigint, _Goal]>;
}): {
    weeklyPlans: Array<[bigint, WeeklyPlan]>;
    dailyCheckIns: Array<DailyCheckIn>;
    weeklyReviews: Array<WeeklyReview>;
    goalProgress: Array<[bigint, GoalProgress]>;
    goals: Array<[bigint, Goal]>;
} {
    return {
        weeklyPlans: from_candid_vec_n17(_uploadFile, _downloadFile, value.weeklyPlans),
        dailyCheckIns: from_candid_vec_n27(_uploadFile, _downloadFile, value.dailyCheckIns),
        weeklyReviews: from_candid_vec_n30(_uploadFile, _downloadFile, value.weeklyReviews),
        goalProgress: from_candid_vec_n33(_uploadFile, _downloadFile, value.goalProgress),
        goals: from_candid_vec_n41(_uploadFile, _downloadFile, value.goals)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedTasks: Array<_Task>;
    plannedTasks: Array<_Task>;
    progressSummary: string;
}): {
    completedTasks: Array<Task>;
    plannedTasks: Array<Task>;
    progressSummary: string;
} {
    return {
        completedTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.completedTasks),
        plannedTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.plannedTasks),
        progressSummary: value.progressSummary
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desc: string;
    category: [] | [_Type];
    isComplete: boolean;
}): {
    desc: string;
    category?: Type;
    isComplete: boolean;
} {
    return {
        desc: value.desc,
        category: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.category)),
        isComplete: value.isComplete
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedTasks: Array<_Task>;
    missedTasks: Array<_Task>;
    date: bigint;
    goalId: bigint;
}): {
    completedTasks: Array<Task>;
    missedTasks: Array<Task>;
    date: bigint;
    goalId: bigint;
} {
    return {
        completedTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.completedTasks),
        missedTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.missedTasks),
        date: value.date,
        goalId: value.goalId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedTasks: Array<_Task>;
    plannedTasks: Array<_Task>;
    goalId: bigint;
    progressSummary: string;
    weekStart: bigint;
}): {
    completedTasks: Array<Task>;
    plannedTasks: Array<Task>;
    goalId: bigint;
    progressSummary: string;
    weekStart: bigint;
} {
    return {
        completedTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.completedTasks),
        plannedTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.plannedTasks),
        goalId: value.goalId,
        progressSummary: value.progressSummary,
        weekStart: value.weekStart
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyTasks: Array<_Task>;
    weeklyTasks: Array<_Task>;
    milestones: Array<_Milestone>;
}): {
    dailyTasks: Array<Task>;
    weeklyTasks: Array<Task>;
    milestones: Array<Milestone>;
} {
    return {
        dailyTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.dailyTasks),
        weeklyTasks: from_candid_vec_n21(_uploadFile, _downloadFile, value.weeklyTasks),
        milestones: from_candid_vec_n37(_uploadFile, _downloadFile, value.milestones)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desc: string;
    dueDate: [] | [bigint];
}): {
    desc: string;
    dueDate?: bigint;
} {
    return {
        desc: value.desc,
        dueDate: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.dueDate))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    durationDays: bigint;
    createdAt: bigint;
    description: string;
    lockedIn: boolean;
    motivation: string;
    timeFrame: _Type__1;
}): {
    id: bigint;
    durationDays: bigint;
    createdAt: bigint;
    description: string;
    lockedIn: boolean;
    motivation: string;
    timeFrame: Type__1;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        createdAt: value.createdAt,
        description: value.description,
        lockedIn: value.lockedIn,
        motivation: value.motivation,
        timeFrame: from_candid_Type__1_n45(_uploadFile, _downloadFile, value.timeFrame)
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserDataView]): [Principal, UserDataView] {
    return [
        value[0],
        from_candid_UserDataView_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _WeeklyPlan]): [bigint, WeeklyPlan] {
    return [
        value[0],
        from_candid_WeeklyPlan_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _GoalProgress]): [bigint, GoalProgress] {
    return [
        value[0],
        from_candid_GoalProgress_n35(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Goal]): [bigint, Goal] {
    return [
        value[0],
        from_candid_Goal_n43(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_Goal>]): [Principal, Array<Goal>] {
    return [
        value[0],
        from_candid_vec_n49(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<[bigint, _WeeklyPlan]>]): [Principal, Array<[bigint, WeeklyPlan]>] {
    return [
        value[0],
        from_candid_vec_n17(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avoidance: null;
} | {
    other: null;
} | {
    lowEnergy: null;
} | {
    distraction: null;
} | {
    overplanning: null;
}): Type {
    return "avoidance" in value ? Type.avoidance : "other" in value ? Type.other : "lowEnergy" in value ? Type.lowEnergy : "distraction" in value ? Type.distraction : "overplanning" in value ? Type.overplanning : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    months6to12: null;
} | {
    days30: null;
} | {
    days90: null;
} | {
    years1to5: null;
}): Type__1 {
    return "months6to12" in value ? Type__1.months6to12 : "days30" in value ? Type__1.days30 : "days90" in value ? Type__1.days90 : "years1to5" in value ? Type__1.years1to5 : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserDataView]>): Array<[Principal, UserDataView]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _WeeklyPlan]>): Array<[bigint, WeeklyPlan]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyCheckIn>): Array<DailyCheckIn> {
    return value.map((x)=>from_candid_DailyCheckIn_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeeklyReview>): Array<WeeklyReview> {
    return value.map((x)=>from_candid_WeeklyReview_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _GoalProgress]>): Array<[bigint, GoalProgress]> {
    return value.map((x)=>from_candid_tuple_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Milestone>): Array<Milestone> {
    return value.map((x)=>from_candid_Milestone_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Goal]>): Array<[bigint, Goal]> {
    return value.map((x)=>from_candid_tuple_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_Goal>]>): Array<[Principal, Array<Goal>]> {
    return value.map((x)=>from_candid_tuple_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<[bigint, _WeeklyPlan]>]>): Array<[Principal, Array<[bigint, WeeklyPlan]>]> {
    return value.map((x)=>from_candid_tuple_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeeklyPlan>): Array<WeeklyPlan> {
    return value.map((x)=>from_candid_WeeklyPlan_n19(_uploadFile, _downloadFile, x));
}
function to_candid_Milestone_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Milestone): _Milestone {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Type__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desc: string;
    category?: Type;
    isComplete: boolean;
}): {
    desc: string;
    category: [] | [_Type];
    isComplete: boolean;
} {
    return {
        desc: value.desc,
        category: value.category ? candid_some(to_candid_Type_n4(_uploadFile, _downloadFile, value.category)) : candid_none(),
        isComplete: value.isComplete
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desc: string;
    dueDate?: bigint;
}): {
    desc: string;
    dueDate: [] | [bigint];
} {
    return {
        desc: value.desc,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    months6to12: null;
} | {
    days30: null;
} | {
    days90: null;
} | {
    years1to5: null;
} {
    return value == Type__1.months6to12 ? {
        months6to12: null
    } : value == Type__1.days30 ? {
        days30: null
    } : value == Type__1.days90 ? {
        days90: null
    } : value == Type__1.years1to5 ? {
        years1to5: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    avoidance: null;
} | {
    other: null;
} | {
    lowEnergy: null;
} | {
    distraction: null;
} | {
    overplanning: null;
} {
    return value == Type.avoidance ? {
        avoidance: null
    } : value == Type.other ? {
        other: null
    } : value == Type.lowEnergy ? {
        lowEnergy: null
    } : value == Type.distraction ? {
        distraction: null
    } : value == Type.overplanning ? {
        overplanning: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Task>): Array<_Task> {
    return value.map((x)=>to_candid_Task_n2(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Milestone>): Array<_Milestone> {
    return value.map((x)=>to_candid_Milestone_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
